### ISSUE TITLE
ConcurrentQueue::cancellPending() modifies _queue while the wrong mutex is locked

### ISSUE THREAD

**Issue by vedgy** [YACReader/yacreader#201]
`ConcurrentQueue::_queue` is protected by `queueMutex` everywhere but in [`cancellPending()`](https://github.com/YACReader/yacreader/blob/3a9bec55f8f882cf5acd1fb8ccb6eafbd7bd022d/common/concurrent_queue.h#L46).

[`ConcurrentQueue::waitAll()`](https://github.com/YACReader/yacreader/blob/3a9bec55f8f882cf5acd1fb8ccb6eafbd7bd022d/common/concurrent_queue.h#L53) is currently unused. Is `waitAll()` likely to be used somewhere soon? If not, it could be removed along with `jobsLeft`, `_waitVar` and `jobsLeftMutex`. This would greatly simplify the class. If a more feature-full concurrent queue is needed in the future, it might be a good idea to reuse some tested and tried implementation, such as [`QtConcurrent::run`](https://doc.qt.io/qt-5/qtconcurrentrun.html) (possibly with a dedicated thread pool).

**Comment by luisangelsm** [comment]
Fixed [here](https://github.com/YACReader/yacreader/commit/4c93c70de6249678f77e12f94a12f1a7e2b2eabd).

Yes, the class as it is will be used in the future, I have a few things in mind that I would like to be pure c++.

**Comment by vedgy** [comment]
Not really fixed. `jobsLeft` is also modified in this function, so `jobsLeftMutex` must also be locked. Possibly in separate code blocks to avoid locking both mutexes at the same time and reduce the risk of a deadlock. On the other hand, there might be reason to update both data members in a single transaction (while both mutexes are locked). More careful analysis is needed to tell for sure. Also note that there might be other bugs in the current complex code, especially in its currently unused parts.

Maybe it would be better to use an existing implementation such as `QtConcurrent` or https://github.com/cameron314/concurrentqueue. It could be faster too, especially a lock-free queue.

**Comment by luisangelsm** [comment]
Ok, now.

As I said I would like to have some pure c++ solution to use in code that I want to keep isolated from Qt in the future.

**Comment by vedgy** [comment]
I wonder - is `waitAll()` really very useful and worth the added complexity? Such a function isn't very common in other concurrent queue implementations, which is why replacing it with a ready-made solution could be a problem. Maybe other concurrent queues don't provide this capability for a good reason? The user of the `ConcurrentQueue` could determine that all jobs are done in a different (custom) way, such as decrementing the number of assigned jobs inside the `job` and emitting a signal once that number reaches 0.

**Comment by luisangelsm** [comment]
It is useful when you have to enqueue groups of jobs that need to be completed before the next group is queued. And it has been extensively used in other projects.

It is just a convenience small class that has been useful to me in the past, it is not supposed to be a fully concurrent system.

**Comment by vedgy** [comment]
It's difficult to tell how this class may or may not be used, because it lacks documentation. At first glance, the implementation seems to be thread-safe and the class looks usable from multiple threads concurrently. However, `cancellPending()` and `waitAll()` can't be safely called from different threads:
1) suppose that `waitAll()` is called while a job is running, and the calling thread starts waiting on `_waitVar`;
2) then in another thread `cancellPending()` is called and sets `jobsLeft` to 0.
3) `nextJob()` completes a job, decrements `jobsLeft` to -1 and notifies `_waitVar`.
4) `waitAll()` then waits forever for `jobsLeft` to become 0.

This API race could be fixed by reducing `jobsLeft` by `_queue.size()` rather than setting it to 0 in `cancellPending()`. This would also allow to use the `ConcurrentQueue` object after a call to `cancellPending()` (currently `jobsLeft` can end up wrong, even negative, breaking `ConcurrentQueue`'s invariants).

On another note, `_waitVar.notify_one()` could be replaced with `_waitVar.notify_all()` to allow calling `waitAll()` from multiple threads. Though that wouldn't be reliable if one of the waiting threads immediately enqueues a new job.

> It is useful when you have to enqueue groups of jobs that need to be completed before the next group is queued. And it has been extensively used in other projects.

The implementation doesn't look polished enough to me. But if it has been used elsewhere, there is hope that it has no more bugs :)

**Comment by vedgy** [comment]
A few days ago I realized that `ConcurrentQueue` class is hardly usable without the `waitAll()` member function I proposed to remove. Since `~ConcurrentQueue()` cancels all jobs, there is no way to wait for them to complete. A simpler alternative to `waitAll()` could be a public `join()` member function that joins threads w/o canceling the jobs. The downside of this alternative is the introduction of a *null state* into `ConcurrentQueue`, though it won't complicate the code nearly as much as the current `waitAll()` implementation (a simple `if` check or an assertion that the first thread is `joinable()` in each public member function would work). @luisangelsm, any chance this simplification would work for your planned use cases?

I have started writing [Qt tests](https://doc.qt.io/qt-5/qtest-overview.html) for `ConcurrentQueue`. Some of the tests fail because of existing bugs I have described in the previous comment. Unless you settle for the simplicity of the `join()` atlernative described above, I'll fix the bugs and try to simplify the code that `waitAll()` requires.

**Comment by luisangelsm** [comment]
Start adding unit tests to the project is something I have been wanting for a long time. If you have them running already, do you mind to setup them in CI? A separated job after code format validation probably or a separated step, I didn't think about it yet, if tests pass then we can start building the binaries for all platforms.

**Comment by luisangelsm** [comment]
I didn't see if Qt6 has introduce any changes in test but it would be nice to double check it to avoid using any stuff that is deprecated or dropped in Qt6

**Comment by selmf** [comment]
@vedgy If you are interested in unit testing, could you take a look at this? https://machinekoder.com/qt-unit-testing-catch-trompeloeil/

As we'll likely have to support both Qt5 and Qt6 for some time in the future, we're interested in a testing solution that does not depend on a specific version of Qt and that is a good fit to test non-qt code too. Catch plus Trompeloeil seems a good fit, so if you'd give this a go and report back this would be a great help for us.

**Comment by vedgy** [comment]
> As we'll likely have to support both Qt5 and Qt6 for some time in the future, we're interested in a testing solution that does not depend on a specific version of Qt and that is a good fit to test non-qt code too.

I have some experience with Qt Test. I am pretty sure there won't be trouble with supporting both Qt versions. See for example the very short [Changes to Qt Test in Qt 6 article](https://doc.qt.io/qt-6/testlib-changes-qt6.html). The greatest disadvantage of Qt Test is not a dependency on a specific Qt version and not that it can't test non-Qt code. This testing framework is just not very powerful and may be more cumbersome/verbose to use compared to specialized testing frameworks. The upside is that no extra dependencies are required, and it supports Qt types very well.

Catch2 looks good now that it supports data-driven testing via [generators](https://github.com/catchorg/Catch2/blob/devel/docs/generators.md). The only obvious downside of Catch2 compared to Qt Test is longer compilation times. Catch2 v3 that is currently still in development [promises](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md) to significantly reduce compilation time. Since we just start using Catch, perhaps it makes sense to use the latest development version even if it is not very stable yet?

I don't know about Trompeloeil because I have no experience with mocks. For now I am going to convert my Qt tests to Catch2 and see how well that works. If someone needs the power of Trompeloeil, they can add it later.

@luisangelsm, please answer my question on whether the `ConcurrentQueue::join()` simplification is acceptable to let me know what to test and fix.

**Comment by selmf** [comment]
I don't see any reason not to try Catch2 v3 if it suits our needs. The preferred way to add this to our build will be an embedded copy in our third_party directory anyways, so we are in control of what we use. I agree that Trompeloeil should be added as needed.

**Comment by luisangelsm** [comment]
@vedgy I would prefer to keep the `waitAll`. The queue objects are not intended to be shared between threads so no need to test/fix that part, maybe just add a comment to the class.

There are 2 scenarios mainly, 1) enqueue async tasks with potential for cancellation and 2) parallelize N jobs and wait for them.

As you know this is only used in a couple of places for now, I didn't want to commit to a Qt based solution yet, because I am not sure what would be better, use Qt or try to use a pure c++ solution.

About c++17, since Qt6 adopts c++17 and we want to move in that direction I think it is reasonable to start using it too.
